---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  annotations:
    kubernetes.io/change-cause: "update to phpmyadmin"
spec:
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type:  RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1.24"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
